# Research Background

Post-fire debris flows (PFDF) represent one of the most destructive and potentially hazardous consequences associated with increasing wildfire severity. While the abundance of literature has explored the initiation processes and generation of PFDFs, investigations into their downstream impacts are limited. Modeling frameworks have begun to investigate the downstream impacts of post-fire erosion by predicting where PFDF sediment is generated post-wildfire, how much of that sediment is delivered to a stream channel, and how that pulse of sediment propagates downstream through the river network. While most inputs to such modeling frameworks are available through open source datasets, a significant gap still exists regarding the grain size distributions (GSD) of PFDFs and the factors influencing these GSDs. This presents a major obstacle in developing watershed-scale wildfire risk assessment models, as GSD exerts a first-order control on the rates and modes of sediment transport through a river network. Additionally, while models exist to predict the volumes of sediment deposited by PFDFs, the most prominent volume-prediction model (Gartner et al., 2014) was calibrated using data from Southern California. We therefore have a limited understanding of how this model functions in other regions. We have compiled GSDs and volume data from previous wildfire studies and conducted new fieldwork measuring GSDs and deposit volumes in PFDF deposits to fill this critical knowledge gap. Adding to the 25 GSDs and the 13 volume measurements from previous studies spanning the Intermountain West, we measured GSDs and volumes from an additional 30 PFDFs that occurred in 10 different wildfires across Utah. Altogether this represents the largest and most spatially extensive dataset of PFDF GSDs of which we are aware. Catchments that produced these PFDFs vary in upstream burn severity, area, slope, forest type, soils, climate, and geology. These metrics were all extracted as potential predictor variables for our statistical analysis. We will analyze these data using Random Forest and Multiple Linear Regression statistical modeling and investigate which landscape metrics exert the most control on PFDF GSD and volumes in the Intermountain West. We aim to generalize the results of our GSD model and to validate existing PFDF volume models for this region.

## Research Questions

1. How much variance is there in post-fire debris flow grain sizes between different fans?

2. How well do the Gartner et al. (2008; 2014) models apply to debris flows in the Intermountain West?



